network/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name="network"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("profile_regis", views.profile_regis, name="profile_regis"),

    # API Routes
    path("generate_post", views.generate_post, name="generate_post" ),
    path("post/<int:post_id>", views.post, name="post"),
    path("profile", views.profile, name="profile")
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

social_network/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import UniqueConstraint


class User(AbstractUser):
    pass

class Profile(models.Model):
    SEX_CHOICES = [('M', 'Male'), ('F', 'Female'), ('O', 'Other')]
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='rel_profile')
    username = models.CharField(max_length=36, unique=True)
    bio = models.TextField(max_length=280)
    profile_pic = models.ImageField(upload_to='profile_pics/')
    birth_date = models.DateField()
    sex = models.CharField(max_length=1, choices=SEX_CHOICES)
    following = models.ManyToManyField("self", symmetrical=False, related_name='followers', blank=True)

    def serialize(self):
        return {
            "id": self.id,
            "username": self.username,
            "bio": self.bio,
            "profile_pic": self.profile_pic.url,
            "birth_date": self.birth_date,
            "sex": self.get_sex_display(),  # Display the human-readable version of 'sex'
            "followers": self.followers.count() if self.followers.exists() else 0,
            "following": self.following.count() if self.following.exists() else 0
        }
    
    def __str__(self):
        return f'{self.username}'


class Post(models.Model):
    id = models.AutoField(primary_key=True)
    creator = models.ForeignKey("Profile", on_delete=models.CASCADE, related_name="posts")
    post_nb = models.IntegerField()  # unique post number for user, alternative to id
    message = models.TextField(max_length=280)
    ping_users = models.ManyToManyField("Profile", related_name='pinged_posts')
    timestamp = models.DateTimeField(auto_now_add=True)
    is_del = models.BooleanField(default=False)
    is_arch = models.BooleanField(default=False)
    is_reported = models.ManyToManyField("Profile", related_name='reports', blank=True)
    is_edited = models.ManyToManyField("Edit", related_name='edited_posts', blank=True)
    repost_source = models.ForeignKey("self", null=True, blank=True, on_delete=models.SET_NULL, related_name='reposts')

    class Meta:
        constraints = [
            UniqueConstraint(fields=['creator', 'post_nb'], name='unique_post_nb_per_user')
        ]

    def save(self, *args, **kwargs):
        # Only assign post_nb if it is not already set
        if self.post_nb is None:
            # Get the last post for this user
            last_post = Post.objects.filter(creator=self.creator).order_by('post_nb').last()
            # Set post_nb as one greater than the last post_nb, or 1 if no posts exist
            self.post_nb = last_post.post_nb + 1 if last_post else 1
        super().save(*args, **kwargs)

    def is_repost(self):
        return self.repost_source is not None

    def serialize(self):
        return {
            "id": self.id,
            "post_number": self.post_nb,
            "creator": self.creator.username,
            "message": self.message,
            "pinged_users": [user.username for user in self.ping_users.all()],
            "timestamp": self.timestamp.strftime("%b %d %Y, %I:%M %p"),
            "is_reported": [user.username for user in self.is_reported.all()],
            "is_del": self.is_del,
            "is_arch": self.is_arch,
            "is_edited": [edit.id for edit in self.is_edited.all()],
            "repost_source": self.repost_source.id if self.repost_source else None,
            "is_repost": self.is_repost()
        }

    def __str__(self):
        return f'{self.creator.user.username} post:{self.post_nb}'



class SavedPost(models.Model):
    user = models.ForeignKey("Profile", on_delete=models.CASCADE, related_name="saved_post")#the user who saves the post
    timestamp = models.DateTimeField(auto_now_add=True)# the date and time it was saved once button clicked
    is_saved = models.BooleanField(default=False)# the post is saved
    post = models.ForeignKey("Post", on_delete=models.CASCADE, related_name="post")# the post that is saved


class Edit(models.Model):
    post = models.ForeignKey("Post", on_delete=models.CASCADE, related_name="edit")
    edited_message = models.TextField(max_length=280)
    edited_at = models.DateTimeField(auto_now_add=True)
    editor = models.ForeignKey("Profile", on_delete=models.CASCADE, related_name="edit")


class Tag(models.Model):
    Author = models.ForeignKey("Profile", on_delete=models.CASCADE, related_name="tags")
    posts = models.ManyToManyField("Post", related_name="tags")
    reference = models.IntegerField(default=0)
    name = models.CharField(max_length=64, unique=True) 
    timestamp = models.DateTimeField(auto_now_add=True)

    # a method so that everytime a tag is created,  add one to  reference or if exists add one to current reference
    def add_reference(self):
        self.reference += 1
        self.save()
    
    def __str__(self):
        return f'{self.name} ({self.reference})'
    




class PostImages(models.Model):
    post = models.ForeignKey("Post", on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(upload_to='images/')
    image_ref = models.IntegerField(default=0)

    def __str__(self):
        return f'pic_{self.post}_{self.image_ref}'
    



class Comment(models.Model):
    Author = models.ForeignKey("Profile", on_delete=models.CASCADE, related_name="mycomment")
    body = models.TextField(max_length=120)
    timestamp = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey("Post", on_delete=models.CASCADE, related_name="comments")

class Reaction(models.Model):
    user = models.ForeignKey("Profile", on_delete=models.CASCADE, related_name="reactions")
    post = models.ForeignKey("Post", on_delete=models.CASCADE, related_name="reaction")
    like = models.BooleanField(default=False)
    dislike = models.BooleanField(default=False)
    love = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

class Notification(models.Model):
    user = models.ForeignKey("Profile", on_delete=models.CASCADE, related_name="notifications")
    message = models.TextField(max_length=32)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

network/forms.py
from django import forms
from network.models import Profile

class ProfileForm(forms.ModelForm):
    birth_date = forms.DateField(widget=forms.DateInput(attrs={'type':'date'}), required=True)

    class Meta:
        model = Profile
        fields = ['bio', 'profile_pic', 'birth_date', 'sex']
        

network/views.py
import json
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from network.extra.extra import *
from django.core.exceptions import ValidationError

from .models import User, Profile, Post, Tag, PostImages

from network.forms import ProfileForm

def index(request):
    if request.user.is_authenticated:
        return render(request, "network/index.html")
    
    else:
        return HttpResponseRedirect(reverse("network:login"))


@csrf_exempt
@login_required
def generate_post(request):
    if request.method != "POST":
        return JsonResponse({"error": "POST request required."}, status=400)

    try:
        message = request.POST.get("message", "")
        images = request.FILES.getlist("images")

        tags = rip_tags(message)  # Extract tags from message

        # Extract pinged users from message
        pinged_usernames = rip_pings(message)
        pinged_users = Profile.objects.filter(user__username__in=pinged_usernames)

        # Create the post
        post = Post.objects.create(
            creator=request.user.rel_profile,
            message=message
        )
        post.save()

        # Set `ping_users` with Profile instances (not strings)
        post.ping_users.set(pinged_users)
        post.save()

        # Associate tags with the post
        if tags:
            for tag_name in tags:
                tag, created = Tag.objects.get_or_create(name=tag_name, Author=request.user.rel_profile)
                if not created:
                    tag.add_reference()  # Increase reference count if tag already exists
                post.tags.add(tag)  # Link tag to post

        # Handle saving images
        for i, image in enumerate(images):
            PostImages.objects.create(
                post=post,
                image=image,
                image_ref=i
            )

        return JsonResponse({"message": "Post created successfully."}, status=201)

    except ValidationError as e:
        return JsonResponse({"error": str(e)}, status=400)
    except Exception as e:
        return JsonResponse({"error": "An unexpected error occurred: " + str(e)}, status=500)


def profile_regis(request):
    if request.method == 'POST':
        # Save the form data
        form  = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.username = request.user.username
            profile.birth_date = form.cleaned_data["birth_date"]
            profile.sex = form.cleaned_data["sex"]
            profile.save()
            return HttpResponseRedirect(reverse("network:index"))
    else: 
        form = ProfileForm()


def post(request, post_id):
    ...

def profile(request):
    user = request.user
    profile_form = ProfileForm()
    if not user.is_authenticated:
        return JsonResponse({"error": "Username not found or required."}, status=400)
    try:
        profile = user.rel_profile
    except Profile.DoesNotExist:
        return render(request, "network/profile_editor.html", {"username": user.username, "form": profile_form})
    
    return render(request, "network/profile.html", {"username": user.username, "profile": profile})


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("network:index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("network:index"))


def register(request):
    if request.method == "POST":
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username=username, email=email, password=password, first_name=first_name, last_name=last_name)
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("network:profile"))
    else:
        return render(request, "network/register.html")

network/templates/network/index.html
{% extends "network/layout.html" %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'network/assets/dist/css/post.css' %}">
{% endblock %}

{% block title %}Feed{% endblock%}

{% block body %}
<div class="container">
    <div class="d-flex align-items-center justify-content-between">
        <div class="d-flex justify-content-center w-100">
            <div>
                <button class="btn btn-sm btn-outline-primary" id="ForYou">For You</button>
                <button class="btn btn-sm btn-outline-primary" id="Following">Following</button>
            </div>
        </div>
        <div id="air-btns">
            <button class="btn btn-sm btn-outline-primary" id="compose-btn">+</button>
        </div>
    </div>
    
    <div id="feed">
        <div id ="homepage">
        </div>


        <div id="compose-post" class="post-container">
            <h3>What comes to your mind?</h3>
            <form id="compose-post-form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-message">
                    <textarea id="post-message" placeholder="Write here..."></textarea>
                </div>
                <div class="form-buttons">
                    <label for="upload-images" class="btn btn-outline-primary">
                        <i class="fas fa-camera"></i> Upload Images
                    </label>
                    <input type="file" id="upload-images" name="images" multiple accept="image/*">
                    <div id="postPreview" class="post-preview"></div>
                </div>
                
                <div class="primary-buttons">
                    <input  id="submitPost" value="Postar" type="submit" class="btn btn-primary"/>
                </div>
            </form>
        </div>
    </div>

    <div id="compose-repost">
    </div>
</div>
{% endblock %}

{% block script %}
    <script type="module"  src="{% static 'network/main.js' %}"></script>
{% endblock %}

network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <script src="{% static 'network/assets/js/color-modes.js' %}"></script>
        
        <title>{% block title %}Social Network{% endblock %}</title>
        
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        <script src="{% static 'network/search.js' %}"></script>
        {% block script %}
        {% endblock %}
        <link href="{% static 'network/assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'network/headers.css' %}" rel="stylesheet">
        <link href="{% static 'network/styles.css' %}" rel="stylesheet">
        <!-- Custom styles for this template -->
        {% block style %}
        {% endblock %}
    </head>
    <body>
        <!-- THEME-->
        <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
            <symbol id="check2" viewBox="0 0 16 16">
              <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
            </symbol>
            <symbol id="circle-half" viewBox="0 0 16 16">
              <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
            </symbol>
            <symbol id="moon-stars-fill" viewBox="0 0 16 16">
              <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
              <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
            </symbol>
            <symbol id="sun-fill" viewBox="0 0 16 16">
              <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
            </symbol>
        </svg>
      
        <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
          <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
                  id="bd-theme"
                  type="button"
                  aria-expanded="false"
                  data-bs-toggle="dropdown"
                  aria-label="Toggle theme (auto)">
              <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
              <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
          </button>
          <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
            <li>
              <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
                  <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#sun-fill"></use></svg>
                  Light
                  <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
              </button>
            </li>
            <li>
              <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
                  <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
                  Dark
                  <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
              </button>
            </li>
            <li>
              <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
                  <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#circle-half"></use></svg>
                  Auto
                  <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
              </button>
            </li>
          </ul>
        </div>
        <!-- END THEME -->


        <main>
          <header class="p-3 mb-3 border-bottom">
            <div class="container">

              {% if user.is_authenticated %}
                <div class="d-flex flex-wrap align-items-center justify-content-between">
                  
                  <div id="left-interact" class="d-flex align-items-center">
                    <div id="search-area" style="display: none;">
                      <form role="search" class="d-flex align-items-center ms-2">  
                        <button id="search-area-left" class="btn p-10 link-body-emphasis" type="button"><i class="fas fa-arrow-left"></i></button>
                        <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
                      </form>
                    </div>
                    <div>
                      <button id="search-area-button" class="btn p-10 link-body-emphasis"><i class="fas fa-search"></i></button>
                    </div>
                  </div>

                  <div id="center-interact" class="d-flex justify-content-center flex-grow-1" style="margin-left: 40%;">
                    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                        <li><a href="{% url 'network:index' %}" class="nav-link px-2 link-body-emphasis"><img src="{% static 'network/assets/icones/Gaamblack.svg' %}" width="100" height="30"/></a></li>
                    </ul>
                  </div>

                  <div id="right-interact" class="d-flex align-items-center">
                    <ul id="myfollow" class="nav col-12 col-lg-auto me-lg-3 mb-2 justify-content-center mb-md-0">
                      <li>
                          <a href="#" class="nav-link px-2 link-body-emphasis">
                              <span style="color: #FF5733; font-weight: bold;">{{ user.rel_profile.followers.count }}</span> Following
                          </a>
                      </li>
                      <li>
                          <a href="#" class="nav-link px-2 link-body-emphasis">
                              <span style="color: #3399FF; font-weight: bold;">{{ user.rel_profile.following.count }}</span> Followers
                          </a>
                      </li>
                    </ul>
                  
                      
                    <div id="drop" class="dropdown text-end ms-3">
                      <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{{ user.rel_profile.profile_pic.url }}" alt="mdo" width="32" height="32" class="rounded-circle">
                      </a>
                      <ul class="dropdown-menu text-small">
                        <li>
                          <form action="{% url 'network:profile' %}" method="post" style="display: inline;">
                              {% csrf_token %}
                              <button type="submit" class="dropdown-item fw-bold fs-6" style="border: none; background: none; text-align: left; width: 100%;">
                                  {{ user.first_name }} {{ user.last_name }}
                                  <p class="text-muted" style="display: block; font-size: small;">@{{ user.username }}</p>
                              </button>
                          </form>
                        </li>
                        <li><a class="dropdown-item" href="#">Saved Items</a></li>
                        <li><a class="dropdown-item" href="#">Settings</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'network:logout' %}">Sign out</a></li>
                      </ul>
                    </div>
                  </div>

                </div>
              {% endif %}
            </div>
          </header>
          <div class="body">
              {% block body %}
              {% endblock %}
          </div>

        </main>
        <script src="{% static 'network/assets/dist/js/bootstrap.bundle.min.js' %}"></script>

    </body>
</html>

network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'network:register' %}">Register here.</a>

{% endblock %}

network/templates/network/profile.html
{% extends "network/layout.html" %}

{% load static %}

{% block title %} {{request.user.username}} {% endblock %}

{% block body %}
<div class="container">
    <div id ="Profile">
    </div>

    <button class="btn btn-sm btn-outline-primary" id="All">All</button>
    <button class="btn btn-sm btn-outline-primary" id="MyComments">Mycomments</button>
    <button class="btn btn-sm btn-outline-primary" id="Reposts">Reposts</button>
    <button class="btn btn-sm btn-outline-primary" id="Saved">Saved</button>

    <div id="my-content">
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'network/profile.js' %}"></script>
{% endblock %} 

network/templates/network/profile_editor.html
{% extends "network/layout.html" %}

{% load static %}

{% block body %}
<div class="container">
    <h2>Profile</h2>
    
    <div id="reg_profile">
        <form action="{% url 'network:profile_regis' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            <!-- Bio Field -->
            <div class="form-group" id="bio">
                {{ form.bio.label_tag }}
                {{ form.bio }}
            </div>
            
            <!-- Profile Picture Field -->
            <div class="form-group" id="profile_pic">
                <label for="profile_pic">Upload Profile Picture</label>
                {{ form.profile_pic }}
            </div>
            
            <!-- Birth Date Field -->
            <div class="form-group" id="birth_date">
                <label for="birth_date">Birth Date</label>
                {{ form.birth_date }}
            </div>
            
            <!-- Sex Field -->
            <div class="form-group" id="sex">
                <label for="sex">Choose your gender</label>
                {{ form.sex }}
            </div>
    
            <!-- Submit Button -->
            <input class="btn btn-primary" type="submit" value="Save">
        </form>
    </div>
    
    
</div>

{% block script %}
<script src="{% static 'network/profile_editor.js' %}"></script>
{% endblock %}


{% endblock %}

network/templates/network/register.html
{% extends "network/layout.html" %}

{% load static %}

{% block body %}
 <div id="reg_user">
    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}
    <div>
        <form action="{% url 'network:register' %}" method="post">
            {% csrf_token %}

            <div class="form-group">
                <input class="form-control" autofocus type="text" name="first_name" placeholder="Your First name">
            </div>
            <div class="form-group">
                <input class="form-control"  type="text" name="last_name" placeholder="Your Last name">
            </div>
            <div class="form-group">
                <input class="form-control"  type="text" name="username" placeholder="Username">
            </div>
            <div class="form-group">
                <input class="form-control" type="email" name="email" placeholder="Email Address">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
            </div>
            <input class="btn btn-primary" type="submit" value="Register">
        </form>
        Already have an account? <a href="{% url 'network:login' %}">Log In here.</a>
    </div>
</div>
{% endblock %}